jineegram_project/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^post/', include('post.urls', namespace='post')),
    url(r'^member/', include('member.urls', namespace='member')),
]

urlpatterns += static(
	settings.MEDIA_URL,
	document_root=settings.MEDIA_ROOT
)

member/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^login/$', views.login, name='login'),
    url(r'^logout/$', views.logout, name='logout'),
    url(r'^signup/$', views.signup, name='signup'),
]

post/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.post_list, name='post_list'),
    url(r'^(?P<post_pk>\d+)/$', views.post_detail, name='post_detail'),
    url(r'^create/$', views.post_create, name='post_create'),
    url(r'^(?P<post_pk>\d+)/like-toggle/$', views.post_like_toggle, name='post_like_toggle'),
    url(r'^(?P<post_pk>\d+)/comment/create/$', views.comment_create, name='comment_create'),
]

member/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.contrib.auth.models import AbstractUser
from django.db import models


class User(AbstractUser):
    GENDER_MALE = 'm'
    GENDER_FEMALE = 'f'
    GENDER_OTHER = 'o'
    CHOICES_GENDER = (
        (GENDER_MALE, '남성'),
        (GENDER_FEMALE, '여성'),
        (GENDER_OTHER, '기타'),
    )
    img_profile = models.ImageField(upload_to='user', blank=True)
    gender = models.CharField(max_length=1, choices=CHOICES_GENDER)
    like_posts = models.ManyToManyField('post.Post', blank=True, related_name='like_users')

    class Meta:
        ordering = ['-pk']

    def __str__(self):
        return self.username

post/models.py
from django.db import models
from django.conf import settings
# Create your models here.

class Post(models.Model):
    author = models.ForeignKey(settings.AUTH_USER_MODEL)
    photo = models.ImageField(upload_to='post')
    
    def __str__(self):
        return f'Post (PK: {self.pk}, Author: {self.author.username})'

    class Meta:
        ordering = ['-pk']


class Comment(models.Model):
    post = models.ForeignKey(Post)
    author = models.ForeignKey(settings.AUTH_USER_MODEL)
    content = models.TextField()

    def __str__(self):
        return f'Comment (PK: {self.pk}, Author: {self.author.username})'


    class Meta:
        ordering = ['-pk']

member/forms.py
from django import forms
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm

User = get_user_model()


class LoginForm(AuthenticationForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        class_update_fields = ['username', 'password']
        for field_name in class_update_fields:
            self.fields[field_name].widget.attrs.update({
                'class': 'form-control'
            })


class SignupForm(UserCreationForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        class_update_fields = ['password1', 'password2']
        for field_name in class_update_fields:
            self.fields[field_name].widget.attrs.update({
                'class': 'form-control'
            })

    class Meta:
        model = User
        fields = (
            'username',
            'password1',
            'password2',
            'img_profile',
            'gender',
        )
        widgets = {
            'username': forms.TextInput(
                attrs={
                    'class': 'form-control',
                }
            ),
            'gender': forms.Select(
                attrs={
                    'class': 'form-control',
                }
            ),
        }

post/forms.py
from django import forms
from .models import Comment, Post

class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = (
            'photo',
        )


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = (
            'content',
        )
        widgets = {
            'content': forms.TextInput(
                attrs={
                    'class': 'content',
                    'placeholder': '댓글 달기...',
                }
            )
        }

    def clean_content(self):
        data = self.cleaned_data['content']
        errors = []
        if data == '':
            errors.append(forms.ValidationError('댓글 내용을 입력해주세요'))
        elif len(data) > 50:
            errors.append(forms.ValidationError('댓글 내용은 50자 이하로 입력해주세요'))
        if errors:
            raise forms.ValidationError(errors)
        return data

member/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.shortcuts import render, redirect
from django.contrib.auth import login as django_login, logout as django_logout, authenticate

from .forms import LoginForm, SignupForm
from .serializers import UserSerializer

def login(request):
    if request.method == 'POST':
        next = request.GET.get('next')

        login_form = LoginForm(request=request, data=request.POST)

        if login_form.is_valid():
            user = login_form.get_user()
            django_login(request, user)
            return redirect(next if next else 'post:post_list')
        login_form.add_error(None, '아이디 또는 비밀번호가 올바르지 않습니다')
    else:
        login_form = LoginForm()

    context = {
        'login_form': login_form,
    }
    return render(request, 'member/login.html', context)


def logout(request):
    django_logout(request)
    return redirect('post:post_list')

def signup(request):
    if request.method == 'POST':
        signup_form = SignupForm(request.POST)
        if signup_form.is_valid():
            user = signup_form.save()
            django_login(request, user)
            return redirect('post:post_list')
    else:
        signup_form = SignupForm()

    context = {
        'signup_form': signup_form,
    }
    return render(request, 'member/signup.html', context)

post/views.py
import os

from django.contrib import messages
from django.shortcuts import render, get_object_or_404, redirect
from django.contrib.auth.decorators import login_required

from utils.decorators import login_required
from .models import Post, Comment
from .forms import CommentForm, PostForm
from .serializers import PostSerializer, CommentSerializer
# Create your views here.

@login_required
def post_create(request):
    if request.method == 'POST':
        post_form = PostForm(request.POST, request.FILES)
        if post_form.is_valid():
            post = post_form.save(commit=False)
            post.author = request.user
            post.save()

            messages.success(request, '사진이 등록되었습니다')
            return redirect('post:post_list')
    else:
        post_form = PostForm()

    context = {
        'post_form': post_form,
    }
    return render(request, 'post/post_create.html', context)


def post_list(request):
	posts = Post.objects.all()
	context = {
		'posts': posts,
	}

	return render(request, 'post/post_list.html', context)


def post_detail(request, post_pk):
    post = get_object_or_404(Post, pk=post_pk)
    comment_form = CommentForm()
    context = {
        'post': post,
        'comment_form': comment_form,
    }
    return render(request, 'post/post_detail.html', context)


@login_required
def comment_create(request, post_pk):
    if request.method == 'POST':
        post = get_object_or_404(Post, pk=post_pk)
        comment_form = CommentForm(request.POST)
        if comment_form.is_valid():
            Comment.objects.create(
                post=post,
                author=request.user,
                content=comment_form.cleaned_data['content']
            )
            return redirect('post:post_list')


@login_required
def post_like_toggle(request, post_pk):
    next_path = request.GET.get('next')
    post = get_object_or_404(Post, pk=post_pk)
    user = request.user

    filtered_like_posts = user.like_posts.filter(pk=post.pk)
    if filtered_like_posts.exists():
        user.like_posts.remove(post)
    else:
        user.like_posts.add(post)

    if next_path:
        return redirect(next_path)
    return redirect('post:post_detail', post_pk=post_pk)

jineegram_project/templates/base.html
{% load static %}
<!doctype html>
<html lang="ko">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <script src="{% static 'js/jquery.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    <title>Instagram</title>
</head>
<body>
    <nav class="top-nav navbar navbar-static-top navbar-default">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#top-nav">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
                <a href="{% url 'post:post_list' %}" class="navbar-brand">Instagram</a>
            </div>

            <div class="collapse navbar-collapse" id="top-nav">
                <form action="" class="navbar-form navbar-left search-hashtag-form" role="search">
                    <div class="form-group">
                        <input type="text" class="form-control search-hashtag-input" placeholder="해시태그 검색...">
                    </div>
                </form>
                <ul class="nav navbar-nav navbar-right">
                    {% if user.is_authenticated %}
                    <li><a href="{% url 'post:post_create' %}">+ Add post</a></li>
                    <li><a href="">Likes</a></li>
                    <li><a href="">Profile</a></li>
                    <li><a href="{% url 'member:logout' %}">Logout</a></li>
                    {% else %}
                    <li><a href="{% url 'member:login' %}">Login</a></li>
                    <li><a href="{% url 'member:signup' %}">Signup</a></li>
                    {% endif %}
                </ul>
            </div>
        </div>
    </nav>
    <div class="container">
        {% if messages %}
            {% for message in messages %}
                <div class="alert-message alert
                    {% if message.tags == 'info' %}
                        alert-info
                    {% elif message.tags == 'success' %}
                        alert-success
                    {% elif message.tags == 'warning' %}
                        alert-warning
                    {% elif message.tags == 'error' %}
                        alert-danger
                    {% endif %}
                    ">{{ message }}</div>
            {% endfor %}
        {% endif %}

        <h1>{% block title %}{% endblock %}</h1>

        {% block content %}

        {% endblock %}
    </div>
</body>
</html>

jineegram_project/templates/include/form.html
<form action="{{ form_action }}" method="post"{% if enctype == 'file' %} enctype="multipart/form-data"{% endif %}>
    {% csrf_token %}
    {% for field in form %}
        <div class="form-group{% if field.errors %} has-error{% endif %}">
            {{ field.label_tag }}
            {{ field }}
            {% if field.errors %}
                {% for error in field.errors %}
                <span class="help-block">{{ error }}</span>
                {% endfor %}
            {% endif %}
        </div>
    {% endfor %}

    {% if form.non_field_errors %}
        {% for error in login_form.non_field_errors %}
        <p class="text-danger"><b>{{ error }}</b></p>
        {% endfor %}
    {% endif %}
    <button class="btn btn-primary btn-block">{{ submit_title }}</button>
</form>

jineegram_project/templates/include/post.html
<div class="panel panel-default post-item">
    {% if post_type == 'list' %}
    <a href="{% url 'post:post_detail' post_pk=post.pk %}">
        <img src="{{ post.photo.url }}" alt="" class="post-image">
    </a>
    {% else %}
        <img src="{{ post.photo.url }}" alt="" class="post-image">
    {% endif %}
    <div class="panel-body">
        {% if post.comments.exists %}
        <ul class="comment-list">
            {% for comment in post.comments.all %}
            <li class="comment">
                <span class="comment-author">{{ comment.author }}</span>
                <span class="comment-content">{{ comment.content }}</span>
            </li>
            {% endfor %}
        </ul>
        <hr>
        {% endif %}
        <form action="{% url 'post:comment_create' post_pk=post.pk %}" method="POST" class="comment-form">
            {% csrf_token %}
            {{ comment_form.content }}
        </form>
    </div>
</div>

jineegram_project/templates/member/login.html
{% extends 'base.html' %}

{% block title %}Login{% endblock %}
{% block content %}
<div class="login">
    {% include 'include/form.html' with form=login_form submit_title='로그인' %}
</div>
{% endblock %}

jineegram_project/templates/member/signup.html
{% extends 'base.html' %}

{% block title %}Signup{% endblock %}
{% block content %}
<div class="signup">
    {% include 'include/form.html' with form=signup_form submit_title='회원가입' %}
</div>
{% endblock %}

jineegram_project/templates/post/post_create.html
{% extends 'base.html' %}

{% block title %}Post create{% endblock %}
{% block content %}
<div class="post-create">
    {% include 'include/form.html' with form=post_form submit_title='등록' enctype='file' %}
</div>
{% endblock %}

jineegram_project/templates/post/post_detail.html
{% extends 'base.html' %}

{% block title %}Post Detail{% endblock %}
{% block content %}
<div>
    {% include 'include/post.html' with post_type='detail' %}
</div>
{% endblock %}

jineegram_project/templates/post/post_list.html
{% extends 'base.html' %}

{% block title %}Post List{% endblock %}
{% block content %}
<div class="row">
	{% for post in posts %}
		<div id="post-{{ post.pk }}">
			{% include 'include/post.html' with post_type='list' %}
		</div>
	{% endfor %}
</div>
{% endblock %}